#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements.
# Requirements:

# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

# Backup /etc/hosts
cp /etc/hosts /etc/hosts.bak

# Add or update entries in /etc/hosts
{
  echo ""
  echo "127.0.0.2 localhost"
  echo "8.8.8.8 facebook.com"
} >> /etc/hosts

# Updated /etc/hosts with custom DNS entries
echo " - localhost -> 127.0.0.2"
echo " - facebook.com -> 8.8.8.8"
